### ISSUE TITLE
why not use Glyphicon Halflings provided with bootstrap 3 ?

### ISSUE THREAD

**Issue by Cyrille37** [dwightwatson/bootstrap-form#116]
Hello,
Thanks very much for your really usefully package :+1: 
But why not using default Glyphicon Halflings provided with bootstrap 3 ?
Cheers.

**Comment by dwightwatson** [comment]
Honestly, I forgot they even had a default icon set. I had only ever used it with Font Awesome which is why the package was built with it out of the box. I suspect the fact that this is the first time it's been brought up suggests that most people use it with Font Awesome too. Either way it's easy enough to change the configuration to use Glyphicons, one line in the config.

**Comment by Cyrille37** [comment]
Thanks
I did not see it's in the configuration, sorry.
Perhaps because `php artisan vendor:publish --provider='\Watson\BootstrapForm\Provider'` does nothing.

Cheers.

**Comment by dwightwatson** [comment]
Is it supposed to? That's not even a class in the package. If you have Laravel 5.6+ you should be able to just call `vendor:publish` and it will ask you which package you want to publish assets for.
