### ISSUE TITLE
model function is protected

### ISSUE THREAD

**Issue by derkgort** [dwightwatson/bootstrap-form#39]
Hi,

I'm getting an error on the model function:

local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to protected method Watson\BootstrapForm\BootstrapForm::model() from context 'Illuminate\Support\Facades\Facade'' in /data/application/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:213

It goes away when changing it to public. Any reason it's protected while the FormBuilder's model function is public?

I'm using php 5.6.13

**Comment by dwightwatson** [comment]
This package uses the `open()` method to open forms, and if a `model` is passed in the associative array of options to that method then it calls upon the protected `model()` method. This `model()` method is different to the one on the Laravel Collective `FormBuilder`.

Check the docs to see how this package works with models, otherwise simply call the `Form` facade (which is the Laravel Collective form builder) instead of the `BootForm` facade to use their model method.
